knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: "%env(resolve:GOOGLE_CLIENT_ID)%"
            client_secret: "%env(resolve:GOOGLE_CLIENT_SECRET)%"
            redirect_route: connect_google_check
            redirect_params: {}

        github:
            type: github
            client_id: "%env(OAUTH_GITHUB_CLIENT_ID)%"
            client_secret: "%env(OAUTH_GITHUB_CLIENT_SECRET)%"
            redirect_route: connect_github_check
            redirect_params: {}
