knp_gaufrette:
    stream_wrapper: ~

    adapters:
        product_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/products"

    filesystems:
        products_fs:
            adapter: product_adapter

vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: products_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
